const aircraftICAOs = {
    "707AF1": "B707",
    "747AF1": "B747",
    "A10 Warthog": "A10",
    "A330 MRTT": "A330",
    "A6M Zero": "ZERO",
    "Airbus A220": "A220",
    "Airbus A320": "A320",
    "Airbus A330": "A330",
    "Airbus A340": "A340",
    "Airbus A350": "A350",
    "Airbus A380": "A380",
    "Airbus Beluga": "BELUGA",
    "An 225": "A225",
    "An22": "AN22",
    "ATR72": "AT72",
    "ATR72F": "AT72",
    "ATR76": "AT76",
    "Avro Vulcan": "VULC",
    "B1 Lancer": "B1",
    "B2 Spirit Bomber": "B2",
    "B29 SuperFortress": "B29",
    "BaggageTruck": "GRND",
    "BaggageTruckSmall": "GRND",
    "Balloon": "BALL",
    "Bell 412": "B412",
    "Bell 412 Rescue": "B412",
    "Blimp": "SHIP",
    "Boeing 707": "B707",
    "Boeing 727": "B727",
    "Boeing 727 Cargo": "B727",
    "Boeing 737": "B737",
    "Boeing 737 Cargo": "B737",
    "Boeing 747": "B747",
    "Boeing 747 Cargo": "B747",
    "Boeing 757": "B757",
    "Boeing 757 Cargo": "B757",
    "Boeing 767": "B767",
    "Boeing 767 Cargo": "B767",
    "Boeing 777": "B777",
    "Boeing 777 Cargo": "B777",
    "Boeing 787": "B787",
    "Bombardier CRJ700": "CRJ7",
    "Bombardier Learjet 45": "LJ45",
    "Bombardier Q400": "Q400",
    "Bus": "GRND",
    "C-32": "B757",
    "C130 Hercules": "C130",
    "C17": "C17",
    "C40": "C40",
    "Caproni Stipa": "ZZZZ",
    "CaravanBlimp": "SHIP",
    "CateringTruck": "GRND",
    "Cessna 172": "C172",
    "Cessna 172 Amphibian": "C172 Seaplane",
    "Cessna 172 Student": "C172",
    "Cessna 182": "C182",
    "Cessna 182 Amphibian": "C182 Seaplane",
    "Cessna 402": "C402",
    "Cessna Caravan": "C208",
    "Cessna Caravan Amphibian": "C208 Seaplane",
    "Cessna Caravan Cargo": "C208",
    "Chinook": "H47",
    "Cirrus Vision": "SF50",
    "Concorde": "CONC",
    "Derek Plane": "ULAC",
    "DHC-6 Twin Otter": "DHC6",
    "DHC-6 Twin Otter Amphibian": "DHC6 Seaplane",
    "Diamond DA50": "DA50",
    "Douglas MD11": "MD11",
    "Douglas MD11 Cargo": "MD11",
    "Douglas MD90": "MD90",
    "DreamLifter": "DREAMLIFTER",
    "E-3 Sentry": "E3",
    "E190": "E190",
    "EC-18B": "C135",
    "English Electric Lightning": "LTNG",
    "Eurofighter Typhoon": "EUFI",
    "Extra 300s": "E300",
    "F/A-18 Super Hornet": "F18",
    "F14": "F14",
   "F15": "F15",
    "F16": "F16",
    "F22": "F22",
    "F35": "F35",
    "F4 Phantom": "F4",
    "F4U Corsair": "CORS",
    "FireTruck": "GRND",
    "Fokker Dr1": "DR1",
    "FollowMeTruck": "GRND",
    "FuelTruck": "GRND",
    "FuelTruckSmall": "GRND",
    "Gripen": "SB39",
    "H135": "EC35",
    "Harrier": "HAR",
    "Hawk T1": "HAWK",
    "Hurricane": "HURI",
    "KC-1": "L101",
    "KC-707": "B707",
    "KC130J": "C30J",
    "KC767": "B767",
    "KingAir 260": "BE20",
    "Lockheed Tristar": "L101",
    "Mig-15": "MG15",
    "Might Walrus": "ZZZZ",
    "P38 Lightning": "P38",
    "P51 Mustang": "P51",
    "P8": "P8",
    "Paratrike": "PARA",
    "Piper Cub": "J3",
    "Piper Cub Amphibian": "J3 Seaplane",
    "Piper PA28181": "PA28",
    "PushBackBig": "GRND",
    "PushBackGreen": "GRND",
    "PushBackSmall": "GRND",
    "Rescue Boat": "ZZZZ",
    "Sikorsky S92": "S92",
    "Sikorsky S92 Coast Guard": "S92",
    "Sled": "SLEI",
    "SR71 BlackBird": "SR71",
    "StairTruck": "GRND",
    "StairTruck737": "GRND",
    "SU27": "SU27",
    "SU57": "SU57",
    "UFO": "ZZZZ",
    "UH-60": "H60",
    "UH-60 Coast Guard": "H60",
    "Wright Brothers Plane": "WF",
};

const airlineICAOs = {
    "Air Canada": "ACA",
    "Air France": "AFR",
    "Air Baltic": "BTI",
    "Delta Air Lines": "DAL",
    "JetBlue": "JBU",
    "Korean Air": "KAL",
    "Qantas": "QFA",
    "Swiss": "SWR",
    "Antonov Airlines": "ADB",
    "American Airlines": "AAL",
    "Aeroflot": "AFL",
    "Air New Zealand": "ANZ",
    "Azul Airlines": "AZU",
    "British Airways": "BAW",
    "Cebu Pacific": "CEB",
    "Condor": "CFG",
    "Lufthansa": "DLH",
    "Aer Lingus": "EIN",
    "Jet2": "EXS",
    "EasyJet": "EZY",
    "Iberia": "IBE",
    "Spirit Airlines": "NKS",
    "Qatar Airways": "QTR",
    "SAS Scandinavian Airlines": "SAS",
    "Thai Airways": "THA",
    "Turkish Airlines": "THY",
    "TUI Airways": "TUI",
    "United Airlines": "UAL",
    "Wizz Air": "WZZ",
    "Cathay Pacific": "CPA",
    "Singapore Airlines": "SIA",
    "KLM": "KLM",
    "Emirates": "UAE",
    "UPS Airlines": "UPS",
    "FedEx": "FDX",
    "Pan Am Airlines": "PAA",
    "DHL": "DHK",
    "LOT Polish Airlines": "LOT",
    "Ryanair": "RYR",
    "Southwest Airlines": "SWA",
    "Bermuda Airways": "BWA",
    "NYT": "NYT",
}

let activeList = aircraftICAOs;

document.getElementById("showAirlines").addEventListener("click", () => {
    activeList = airlineICAOs;
    renderList();
})

document.getElementById("showAircraft").addEventListener("click", () => {
    activeList = aircraftICAOs;
    renderList();
});

function renderList(filterText = "") {
    const container = document.getElementById("search_results");
    container.innerHTML = "";

    Object.keys(activeList).forEach(name => {
        const code = activeList[name];

        if (
            name.toLowerCase().includes(filterText.toLowerCase()) ||
            code.toLowerCase().includes(filterText.toLowerCase())
        ) {
            const item = document.createElement("p");
            item.textContent = `${name} - ${code}`;
            container.appendChild(item);
        }
    });
}

document.getElementById("search").addEventListener("input", (e) => {
    renderList(e.target.value);
});

